/** Manifest gerado por scripts/import-quiz-evidence.sh — não editar paths manualmente. */
export const QUIZ_EVIDENCE_BASE = "/media/quiz-evidence" as const;

export const QUIZ_PROOF_FATURAMENTO = [
  "/media/quiz-evidence/proof/faturamento/fat-01.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-02.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-03.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-04.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-05.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-06.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-07.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-08.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-09.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-10.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-11.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-12.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-13.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-14.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-15.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-16.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-17.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-18.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-19.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-20.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-21.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-22.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-23.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-24.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-25.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-26.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-27.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-28.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-29.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-30.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-31.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-32.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-33.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-34.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-35.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-36.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-37.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-38.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-39.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-40.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-41.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-42.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-43.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-44.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-45.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-46.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-47.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-48.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-49.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-50.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-51.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-52.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-53.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-54.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-55.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-56.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-57.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-58.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-59.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-60.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-61.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-62.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-63.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-64.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-65.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-66.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-67.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-68.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-69.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-70.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-71.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-72.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-73.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-74.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-75.jpeg"
] as const;
export const QUIZ_PROOF_NOTIFICACOES = [
  "/media/quiz-evidence/proof/notificacoes/notif-01.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-02.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-03.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-04.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-05.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-06.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-07.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-08.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-09.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-10.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-100.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-101.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-102.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-103.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-104.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-105.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-106.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-107.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-108.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-109.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-11.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-110.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-111.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-112.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-113.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-114.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-115.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-116.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-117.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-118.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-119.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-12.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-120.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-121.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-122.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-123.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-124.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-125.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-126.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-127.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-128.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-129.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-13.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-130.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-131.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-132.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-133.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-134.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-135.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-136.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-137.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-138.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-139.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-14.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-140.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-141.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-142.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-15.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-16.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-17.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-18.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-19.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-20.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-21.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-22.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-23.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-24.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-25.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-26.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-27.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-28.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-29.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-30.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-31.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-32.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-33.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-34.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-35.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-36.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-37.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-38.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-39.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-40.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-41.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-42.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-43.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-44.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-45.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-46.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-47.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-48.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-49.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-50.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-51.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-52.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-53.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-54.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-55.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-56.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-57.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-58.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-59.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-60.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-61.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-62.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-63.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-64.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-65.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-66.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-67.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-68.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-69.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-70.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-71.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-72.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-73.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-74.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-75.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-76.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-77.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-78.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-79.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-80.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-81.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-82.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-83.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-84.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-85.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-86.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-87.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-88.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-89.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-90.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-91.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-92.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-93.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-94.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-95.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-96.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-97.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-98.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-99.jpeg"
] as const;
export const QUIZ_PROOF_MENCOES_ERICK = [
  "/media/quiz-evidence/proof/mencoes-erick/erick-01.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-02.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-03.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-04.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-05.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-06.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-07.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-08.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-09.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-10.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-11.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-12.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-13.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-14.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-15.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-16.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-17.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-18.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-19.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-20.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-21.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-22.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-23.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-24.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-25.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-26.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-27.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-28.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-29.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-30.jpeg"
] as const;
export const QUIZ_ALL_PROOFS = [
  "/media/quiz-evidence/proof/faturamento/fat-01.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-02.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-03.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-04.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-05.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-06.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-07.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-08.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-09.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-10.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-11.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-12.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-13.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-14.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-15.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-16.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-17.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-18.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-19.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-20.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-21.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-22.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-23.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-24.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-25.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-26.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-27.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-28.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-29.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-30.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-31.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-32.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-33.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-34.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-35.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-36.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-37.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-38.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-39.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-40.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-41.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-42.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-43.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-44.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-45.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-46.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-47.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-48.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-49.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-50.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-51.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-52.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-53.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-54.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-55.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-56.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-57.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-58.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-59.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-60.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-61.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-62.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-63.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-64.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-65.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-66.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-67.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-68.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-69.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-70.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-71.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-72.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-73.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-74.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-75.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-01.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-02.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-03.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-04.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-05.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-06.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-07.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-08.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-09.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-10.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-100.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-101.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-102.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-103.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-104.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-105.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-106.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-107.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-108.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-109.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-11.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-110.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-111.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-112.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-113.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-114.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-115.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-116.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-117.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-118.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-119.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-12.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-120.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-121.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-122.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-123.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-124.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-125.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-126.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-127.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-128.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-129.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-13.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-130.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-131.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-132.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-133.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-134.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-135.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-136.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-137.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-138.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-139.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-14.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-140.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-141.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-142.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-15.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-16.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-17.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-18.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-19.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-20.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-21.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-22.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-23.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-24.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-25.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-26.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-27.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-28.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-29.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-30.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-31.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-32.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-33.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-34.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-35.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-36.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-37.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-38.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-39.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-40.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-41.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-42.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-43.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-44.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-45.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-46.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-47.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-48.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-49.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-50.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-51.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-52.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-53.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-54.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-55.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-56.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-57.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-58.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-59.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-60.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-61.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-62.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-63.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-64.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-65.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-66.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-67.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-68.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-69.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-70.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-71.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-72.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-73.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-74.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-75.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-76.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-77.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-78.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-79.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-80.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-81.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-82.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-83.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-84.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-85.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-86.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-87.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-88.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-89.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-90.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-91.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-92.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-93.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-94.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-95.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-96.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-97.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-98.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-99.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-01.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-02.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-03.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-04.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-05.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-06.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-07.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-08.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-09.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-10.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-11.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-12.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-13.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-14.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-15.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-16.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-17.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-18.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-19.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-20.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-21.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-22.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-23.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-24.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-25.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-26.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-27.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-28.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-29.jpeg",
  "/media/quiz-evidence/proof/mencoes-erick/erick-30.jpeg"
] as const;

/** Prints verticais (WhatsApp / celular) — legíveis em moldura de telefone. */
export const QUIZ_PHONE_LANDING_PROOFS = [
  "/media/quiz-evidence/proof/faturamento/fat-01.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-10.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-116.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-36.jpeg",
] as const;

export const QUIZ_PHONE_PROOFS = [
  "/media/quiz-evidence/proof/faturamento/fat-01.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-10.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-23.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-29.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-116.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-104.jpeg",
  "/media/quiz-evidence/proof/notificacoes/notif-08.jpeg",
  "/media/quiz-evidence/proof/faturamento/fat-36.jpeg",
] as const;

export const QUIZ_LANDING_PROOFS = QUIZ_PHONE_LANDING_PROOFS;
export const QUIZ_INSIGHT_PROOFS: Record<string, string> = {
  "renda_extra": "/media/quiz-evidence/proof/faturamento/fat-01.jpeg",
  "liberdade_fin": "/media/quiz-evidence/proof/faturamento/fat-04.jpeg",
  "liberdade_geo": "/media/quiz-evidence/proof/faturamento/fat-06.jpeg",
  "transicao": "/media/quiz-evidence/proof/notificacoes/notif-03.jpeg",
  "esforco_pouco": "/media/quiz-evidence/proof/faturamento/fat-11.jpeg",
  "pode_mais": "/media/quiz-evidence/proof/notificacoes/notif-09.jpeg",
  "sem_aparecer": "/media/quiz-evidence/proof/mencoes-erick/erick-03.jpeg",
  "sozinho": "/media/quiz-evidence/proof/mencoes-erick/erick-06.jpeg",
  "desconfianca": "/media/quiz-evidence/proof/faturamento/fat-16.jpeg",
  "tempo": "/media/quiz-evidence/proof/notificacoes/notif-102.jpeg",
  "zero": "/media/quiz-evidence/proof/faturamento/fat-02.jpeg",
  "curso_parado": "/media/quiz-evidence/proof/mencoes-erick/erick-09.jpeg",
  "vendendo": "/media/quiz-evidence/proof/faturamento/fat-21.jpeg"
};

export type QuizTestimonialVideo = {
  name: string;
  role?: string;
  quote?: string;
  videoUrl: string;
};

export const QUIZ_TESTIMONIAL_VIDEOS: QuizTestimonialVideo[] = [
  {
    "name": "Aluno",
    "role": "Notificações de venda",
    "quote": "Minhas notificações não param — loja rodando e PIX caindo.",
    "videoUrl": "/media/quiz-evidence/videos/03-video-de-vendas-notificações.mp4"
  },
  {
    "name": "Izabela",
    "role": "Aluno Ascend Club",
    "quote": "Nunca vendi online e hoje recebo PIX toda semana.",
    "videoUrl": "/media/quiz-evidence/videos/06-video-izabela.mp4"
  },
  {
    "name": "Eros",
    "role": "10 vendas",
    "quote": "Bati 10 vendas com a loja que me entregaram pronta.",
    "videoUrl": "/media/quiz-evidence/videos/01-eros-10-vendas.mp4"
  },
  {
    "name": "Renata",
    "role": "Mentoria Erick",
    "quote": "O Erick destrava na hora — não fico mais perdida.",
    "videoUrl": "/media/quiz-evidence/videos/10-video-renata-mensão-erick.mp4"
  },
  {
    "name": "Claudini",
    "role": "Aluno Ascend Club",
    "quote": "Loja pronta, produtos bons — só aprendi a divulgar.",
    "videoUrl": "/media/quiz-evidence/videos/02-video-claudini.mp4"
  },
  {
    "name": "Karen",
    "role": "Aluno Ascend Club",
    "quote": "Trabalho de casa e vendo no meu ritmo.",
    "videoUrl": "/media/quiz-evidence/videos/07-video-karen.mp4"
  },
  {
    "name": "Renata",
    "role": "Sobre as aulas",
    "quote": "As calls ao vivo valem mais que curso gravado.",
    "videoUrl": "/media/quiz-evidence/videos/09-video-renata-falando-das-aulas.mp4"
  },
  {
    "name": "Aluno",
    "role": "Mentoria",
    "quote": "A mentoria ao vivo mudou meu jogo.",
    "videoUrl": "/media/quiz-evidence/videos/08-video-mensão-erick.mp4"
  },
  {
    "name": "Eros",
    "role": "Aluno Ascend",
    "quote": "O método funciona quando você segue o passo a passo.",
    "videoUrl": "/media/quiz-evidence/videos/05-video-eros.mp4"
  },
  {
    "name": "Eros",
    "role": "Resultados",
    "quote": "Resultado real, sem aparecer, vendendo pela internet.",
    "videoUrl": "/media/quiz-evidence/videos/04-video-eros-2.mp4"
  }
];

export const QUIZ_RESULT_PROOFS = QUIZ_PHONE_PROOFS.slice(0, 5);
